index:
    path: /
    methods: GET
    controller: App\Controller\LoginController::index

add_user:
    path: /add_user
    methods: GET
    controller: App\Controller\LoginController::signUp

sign_in:
    path: /enter
    methods: GET
    controller: App\Controller\LoginController::login

login:
    path: /login
    methods: POST
    controller: App\Controller\LoginController::signIn

check_user:
    path: /check
    methods: POST
    controller: App\Controller\UserController::findUser

upload_user:
    path: /user_upload
    methods: POST
    controller: App\Controller\UserController::addNewUser

show_main_page:
    path: /main_page
    methods: GET
    controller: App\Controller\StorefrontController::index

test:
    path: /test
    methods: GET
    controller: App\Controller\UserController::test

make_order:
    path: /make_order
    methods: GET
    controller: App\Controller\StorefrontController::order

order:
    path: /order
    methods: GET
    controller: App\Controller\OrderController::index

thanks:
    path: /thanks
    methods: POST
    controller: App\Controller\OrderController::showThankYouPage

add_pizza:
    path: /add_pizza
    methods: GET
    controller: App\Controller\AddPizzaController::index

store_pizza:
    path: /store_pizza
    methods: POST
    controller: App\Controller\AddPizzaController::add

delete_pizza:
    path: /delete_pizza
    methods: GET
    controller: App\Controller\StorefrontController::deletePizza

logout:
    path: /logout
    methods: GET
    controller: App\Controller\LoginController::logout
