index:
    path: /
    methods: GET
    controller: App\Controller\LoginController::index

add_user:
    path: /add_user
    methods: GET
    controller: App\Controller\LoginController::login

upload_user:
    path: /user_upload
    methods: POST
    controller: App\Controller\UserController::addNewUser

show_user:
    path: /show_user
    methods: GET
    controller: App\Controller\UserController::showUser

update_user:
    path: /update_user
    methods: POST|GET
    controller: App\Controller\UserController::updateUser

delete_user:
    path: /delete_user
    methods: GET
    controller: App\Controller\UserController::deleteUser

all_users:
    path: /all_users
    methods: GET
    controller: App\Controller\UserController::showAllUsers

test:
    path: /test
    methods: GET
    controller: App\Controller\UserController::test